config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}


namespace :admins do
   get 'users/top' => 'users#top', as: 'top'
  resources :users
  resources :topics
  resources :contacts
end

resources :contacts, only: [:create, :destroy]

  resources :users do
     member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  get 'topics/password' => 'topics#password', as: 'topic_password'
  get 'topics/top' => 'topics#top', as: 'top'
  resources :topics do
        member do
      post "add", to: "clips#create"
    end
        collection do
      post 'confirm'
    end
    resources :topic_goods, only: [:create, :destroy]
    resources :topic_bads, only: [:create, :destroy]
    resources :topic_comments, only: [:create, :destroy]
  end

  resources :tags
  resources :categories
  resources :clips, only: [:destroy]

  root 'topics#top'
end

app/models/topic.rb
class Topic < ApplicationRecord
#カウンティング用
is_impressionable
attachment :topic_image

# 記事とユーザーの関係1:N
belongs_to :user

# グッド機能
has_many(:topic_goods, {:dependent => :delete_all})
has_many :good_users, through: :topic_goods, source: :user

# バッド機能
has_many :topic_bads, dependent: :delete_all
has_many :bad_users, through: :topic_bads, source: :user

#コメント機能
belongs_to :user
has_many :topic_comments, dependent: :destroy

#カテゴリー
has_many :topic_categories
has_many :categories, :through => :topic_categories

#タグ機能
has_many :tags, inverse_of: :topic
accepts_nested_attributes_for :tags, allow_destroy: true


# クリップ機能
has_many :clips
has_many :users, through: :clips

validates :title, uniqueness: true
validates :url, uniqueness: true
# validates :tags, associated: true



  def is_new
    (3.days.ago..Time.current).cover?(Time.parse(self.created_at.to_s))
    # (1.minutes.ago..Time.current).cover?(Time.parse(self.created_at.to_s))
  end


  def self.search(search)
      if search.present?
        # binding.pry
        relation = Topic.joins(:tags)
        relations = relation.joins(:categories)
        relations.merge(Category.where(['category_name LIKE ?', "%#{search}%"])).or(relations.where(['tag_name LIKE ?', "%#{search}%"])).or(relations.where(['body LIKE ?', "%#{search}%"])).or(relations.where(['re_body LIKE ?', "%#{search}%"])).or(relations.where(['url LIKE ?', "%#{search}%"])).or(relations.where(['title LIKE ?', "%#{search}%"])).uniq
      else
        Topic.all
      end
  end

  def percentage
    total_count = self.bad_count + self.good_count
    return ((self.good_count.to_f.round(1)/ total_count.round(1) ) * 100).round(1)
  end
end

app/controllers/admins/topics_controller.rb
class Admins::TopicsController < ApplicationController
before_action :authenticate_admin!
layout 'admin.application'

  def index
    @topics = Topic.all.order(created_at: :desc)
  end

private
    def topic_params
      params.require(:topic).permit(:author ,:paragraph,:posted_day, :one_total, :re_body,:title,:url,:body,:topic_image, :tags_attributes => [:id, :tag_name, :topic_id, :_destroy],category_ids: [])
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  helper_method :sort_column, :sort_direction
  require "open-uri"
  require "nokogiri"

  def index
  	# @topics = Topic.page(params[:page]).search(params[:search])

    # @topic = Topic.search(params[:search])
    # @topics = Kaminari.paginate_array(@topic).page(params[:page])
    if params[:search].present?
          @topic = Topic.search(params[:search])
          @topic_search = Topic.search(params[:search])
          @hi_admin = request.url.include?("hi%21admin")
          @iamadmin = request.url.include?("iamadmin")
          if @topic == []
            @topic = Topic.all.order(sort_column + ' ' + sort_direction)
            flash.now[:notice] = "検索に一致する記事がありませんでした。"
          end
    else
      @topic = Topic.all.order(sort_column + ' ' + sort_direction)
    end

    @topics = Kaminari.paginate_array(@topic).page(params[:page]).per(10)

    @good_rank = Topic.find(TopicGood.group(:topic_id).order('count(topic_id) desc').limit(10).pluck(:topic_id))
    @page_rank = Topic.order('page_count DESC').limit(10)
    @user_rank = User.order('follower_count DESC').limit(10)

    @all_good_count = 0
    @all_bad_count = 0
    @total = 0
    @num = 0
    @percent = 0
    @one_total = 0
    @topic.each do |topic|

    # 全体のできない数
      @all_good_count += topic.good_count

    # 全体のできた数
      @all_bad_count += topic.bad_count

    # 個別の記事の投票数
      @num = topic.bad_count + topic.good_count

    # もしカラムを作って保存する場合
    # topic.num == @num

    # 個別の記事の実装可能率
    # @one_total = ((topic.good_count.to_f.round(1)/ (@num).round(1) ) * 100).round(1)


    end
    # 全体の記事の投票数
    @total = @all_bad_count + @all_good_count
    # 全体の記事の実装可能率
    @percent = (@all_good_count.to_f) / (@total)
    @new_topic = Topic.new
    render :layout => 'index.application'
  end


  def confirm
     @topic = Topic.new(topic_params)
     @topic.tags.build
     @topic.user_id = current_user.id
     uri = @topic.url

    unless @topic.valid?(:url)
      flash[:notice] = "重複記事があります。"
      redirect_to topics_path
    else

       if uri == ""
        redirect_to topics_path
       else
   # if @topic.url.uniq == true
    # binding.pry
    # redirect_to topics_path
  # else
       @doc = Nokogiri::HTML(open(uri),nil,"utf-8")
  # =====================================  タイトルについて  ===============================================
        if @doc.css("h1").first != nil
            @h1 = @doc.css("h1").first.text 
        else
            flash[:notice] = "申し訳ありませんが、URLが非対応です。"
            redirect_to topics_path
        end


  # =====================================  タイトルについて  ===============================================
  # =====================================  コードについて    ===============================================
        if @doc.css("pre") != nil
            @pre = @doc.css("pre").text
        else
            flash[:notice] = "申し訳ありませんが、URLが非対応です。"
            redirect_to topics_path
        end
  # =====================================  コードについて  ===============================================
  # =====================================  本文について    ===============================================
        if @doc.css("p") != nil
            @p = @doc.css("p").text
        else
            flash[:notice] = "申し訳ありませんが、URLが非対応です。"
            redirect_to topics_path
        end
  # =====================================  本文について    ===============================================
  # =====================================  記述日について  ===============================================

        if @topic.url.include?("qiita") then
            @time = @doc.css("time").first.text
        elsif @topic.url.include?("teratail") then
            @time = @doc.css("time").first.text
        else
            @time = nil
        end

  # =====================================  記述日について  ===============================================
  # =====================================  著者について    ===============================================

        if  @topic.url.include?("qiita") then
            @author = @doc.xpath('//*[contains(concat( " ", @class, " " ), concat( " ", "it-Header_authorName", " " ))]').text
        elsif @topic.url.include?("teratail") then
            @author = @doc.xpath('//*[@id="l-headContents"]/div/div[2]/div/p[1]/a').text
        else
            @author = nil
        end
      end
    end
 end
# =====================================  著者について  ===============================================

  #    render :new if @topic.invalid?
  # end



  def show
  	@topic = Topic.find(params[:id])
    @topic_good = TopicGood.new()
    @topic_bad = TopicBad.new()
    @topic_comment = TopicComment.new
    impressionist(@topic, nil, :unique => [:session_hash])
    @topic.update(page_count: @topic.impressionist_count)
    @topic.update(good_count: @topic.topic_goods.count)
    @topic.update(bad_count: @topic.topic_bads.count)

    if @topic.percentage.nan?
    @topic.update(total_count: 0)
    else
    @topic.update(total_count: @topic.percentage.to_i)
    end



    # @good_rank = Topic.find(TopicGood.group(:topic_id).order('count(topic_id) desc').limit(10).pluck(:topic_id))

    @num = 0
    @one_total = 0
    # できた、できないの投票数
    @num = @topic.bad_count + @topic.good_count
    # 個別の記事の実装可能率
    # @one_total = ((@topic.good_count.to_f.round(1)/ (@num).round(1) ) * 100).round(0)
  end



  def create
  	@topic = Topic.new(topic_params)
  	@topic.user_id = current_user.id
    @tag_validat = params[:topic][:tags_attributes]["0"][:tag_name]
    @category_validat = params[:topic][:category_ids][1]
    if @tag_validat.blank? || @category_validat.blank?
      flash[:notice] = "タグまたはカテゴリーが入力されていません。"
      redirect_to topics_path
    else @topic.save
      flash[:notice] = "登録完了しました。"
      redirect_to topics_path
    # else
    #   flash[:notice] = "重複記事があります。"
    #   redirect_to topics_path
    end


    # if @topic.save
    # 	redirect_to topics_path
    # else
    #   flash[:notice] = "重複記事があります。"
    #   redirect_to topics_path
    # end
  end


  def edit
  	@topic = Topic.find(params[:id])
    if @topic.user != current_user && admin_signed_in? == false
      redirect_to root_path
    end
  end



  def update
    @topic = Topic.find(params[:id])
    @topic.update(topic_params)
    redirect_to topic_path(@topic.id)
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    flash.now[:notice] = "記事を削除しました。"
    redirect_to topics_path
  end



  def top
     render :layout => false
  end

  def password
    if params[:search].present?
      @topic = Topic.search(params[:search])
       @topic_search = Topic.search(params[:search])
      if @topic == []
        @topic = Topic.all
        flash.now[:notice] = "検索に一致する記事がありませんでした。"
      end
    else
      @topic = Topic.all
    end

    @topics = Kaminari.paginate_array(@topic).page(params[:page]).per(10)

    @good_rank = Topic.find(TopicGood.group(:topic_id).order('count(topic_id) desc').limit(10).pluck(:topic_id))
    @page_rank = Topic.order('page_count DESC').limit(10)
    @user_rank = User.order('follower_count DESC').limit(10)

    @all_good_count = 0
    @all_bad_count = 0
    @total = 0
    @num = 0
    @percent = 0
    @one_total = 0
    @topic.each do |topic|

    # 全体のできない数
      @all_good_count += topic.good_count

    # 全体のできた数
      @all_bad_count += topic.bad_count

    # 個別の記事の投票数
      @num = topic.bad_count + topic.good_count
    end

    @total = @all_bad_count + @all_good_count
    # 全体の記事の実装可能率
    @percent = (@all_good_count.to_f) / (@total)
    @new_topic = Topic.new
    render :layout => 'password.application'
  end


private
    def topic_params
      params.require(:topic).permit(:author ,:paragraph,:posted_day, :total_count, :re_body,:title,:url,:body,:topic_image, :tags_attributes => [:id, :tag_name, :topic_id, :_destroy],category_ids: [])
    end


  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def sort_column
      Topic.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
end

app/helpers/admins/topics_helper.rb
module Admins::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_tag_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.text_field :tag_name,:placeholder => "タグ"   %><%= link_to_remove_association "削除", f %>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="">
	<div class="col-md-8 col-md-offset-2">

		<%= form_for @topic do |f|  %>

			<h3>タイトル</h3><%= f.text_field :title,class: "topic_title" %>

			<h3>記事内本文</h3><%= f.text_area :paragraph ,class: "topic_body" %>

			<h3>記事内コード</h3><%= f.text_area :body ,class: "topic_body" %>


			<h3>修正箇所</h3><%= f.text_area :re_body ,class: "topic_body" %>


			<h3>カテゴリー</h3>
			<%= collection_check_boxes(:topic, :category_ids, Category.all, :id, :category_name) do |b| %>
				<%= b.label { b.check_box + b.text }  %>
			<% end %>


			<h3>タグ</h3>
			<div class="">
				<%= f.fields_for :tags do |tag| %>
					<%= render 'tag_fields', f: tag %>
				<% end %>
				<div class="">
					<%= link_to_add_association '追加', f, :tags %>
				</div>
			</div>

			<h3>画像</h3><%= f.attachment_field :topic_image %>
			<%= f.submit "更新" ,class: "btn btn-default" %>
		<% end %>

	</div>
</div>


<div class="col-md-12 border_line">
</div>

app/views/topics/password.html.erb
<% if user_signed_in? %>
<div class="col-md-12 topic_registration">
<%= form_for @new_topic, url: {action: 'confirm'} do |f|  %>
<%= f.url_field :url,class: "col-md-10" ,:placeholder => "URLで記事を登録できます。" %>
<%= f.submit "登録", class: "col-md-2 btn-default bt-samp31" %>
<% end %>
</div>
<% end %>

<div class="col-md-12 second_nav">
    <div class="col-md-10 col-md-offset-1">

        <div class="col-md-3 col-md-offset-1 second_nav_box">
            <div class="col-md-12 text-center nav_box_text">
             登録ユーザー
            </div>
            <div class="col-md-12 text-center">
              <h2 class="h2_count"><%= User.count %><h6 class="h2_count">人</h6></h2>
            </div>
        </div>

         <div class="col-md-3 col-md-offset-1 second_nav_box">
            <div class="col-md-12 text-center nav_box_text">
              記事総数
            </div>
            <div class="col-md-12 text-center">
              <h2 class="h2_count"><%= Topic.count %><h6 class="h2_count">個</h6></h2>
            </div>
        </div>

        <div class="col-md-3 col-md-offset-1 second_nav_box">
            <div class="col-md-12 text-center nav_box_text">
              <% if @topic_search == nil && "" %>
                  <%= "実装可能率" %>
              <% else %>
                  <%= "検索文字,実装可能率" %>
              <% end %>

            </div>
            <div class="col-md-12 text-center">
             <% if (@percent * 100).round(1).nan? %>
                  <h2 class="h2_count"><%= "0" %><h6 class="h2_count">%</h6></h2>
              <% else %>
                  <h2 class="h2_count"><%= (@percent * 100).round(0) %><h6 class="h2_count">%</h6></h2>
              <% end %>
            </div>
        </div>
    </div>
</div>




<div class="col-md-12 search_area">
        <%= form_tag topics_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search] ,class: "col-md-10 topic_form_index",:placeholder => "記事の検索ができます。" %>
            <%= submit_tag '検索', :name => nil , class: "btn btn-default col-md-2 topic_submit_index bt-samp31" %>
        <% end %>
  </div>


<div class="">
    <div class="col-md-7 col-md-offset-1">
        <h3>記事一覧</h3>
          <% if flash[:notice] %>
        <label style="color:red;"><%= flash[:notice] %></label>
      <% end %>
        <table class="table">
            <tbody>
                <% @topics.each do |topic| %>
                    <tr>
                        <% if topic.percentage.nan? %>
                              <td nowrap rowspan="2"><%= 0 %>%</td>
                          <% else %>
                              <td nowrap rowspan="2"><%= topic.percentage.to_i %>%</td>
                        <% end %>
                        <td class="topic_title_index" colspan="3">
                            <% if topic.is_new %>
                                <label class="new_label">新着</label>
                            <% end %>
                            <%= link_to "#{topic.title}", topic_path(topic),class: "topic_title_index" %></td>
                            
                        <td nowrap ><% if user_signed_in? %><%= link_to "クリップ", add_topic_path(topic.id), method: :post %><% end %></td>

                    </tr>
                    <tr>
                        <td nowrap>
                          <i class="glyphicon glyphicon-thumbs-up"></i><%= topic.good_count %>
                          <i class="glyphicon glyphicon-thumbs-down"></i><%= topic.bad_count %>
                        </td>
                        <td nowrap><%= topic.page_count %>PV</td>
                        <td>
                            <% topic.categories.each do |category| %>
                                <%= link_to "#{category.category_name}", categories_path(category_name: category.category_name)  %>
                            <% end %>
                        </td>
                        <td nowrap><%= topic.user.name %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="col-md-3">
       <h3>ランキング</h3>
        <!-- タブ・メニュー -->
        <ul class="nav nav-tabs">
              <li class="active tab_size"><a class="tab_font_size" href="#sampleContentA" data-toggle="tab">ユーザー</a></li>
              <li class="tab_size"><a class="tab_font_size" href="#sampleContentB" data-toggle="tab">記事</a></li>
              <li class="tab_size"><a class="tab_font_size" href="#sampleContentC" data-toggle="tab">いいね</a></li>
        </ul>

        <!-- タブ内容 -->
        <div class="tab-content">
              <div class="tab-pane active" id="sampleContentA">
                  <table class="col-md-12">
                    <tbody>
                      <% @user_rank.each.with_index(1) do |user_rank, i| %>
                          <tr>
                            <td><%= "第#{i}位" %>：</td>
                            <td><%=link_to "#{user_rank.name}", user_path(user_rank) %></td>
                          </tr>
                          <tr class="ranking_border">
                             <td><%= attachment_image_tag user_rank, :profile_image, size: '50x50', fallback: "no_image_top.jpg", class: "" %></td>
                            <td>followers：<%= user_rank.follower_count %></td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
              </div>


              <div class="tab-pane" id="sampleContentB">
                  <table>
                    <tbody>
                      <% @page_rank.each.with_index(1) do |page_rank, i| %>
                          <tr>
                            <td colspan="2"><%= "第#{i}位" %>：<%=link_to "#{page_rank.title}", topic_path(page_rank) %></td>
                          </tr>
                          <tr class="ranking_border">
                            <td><%= page_rank.user.name %></td>
                            <td>views：<%= page_rank.page_count %></td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
              </div>


              <div class="tab-pane" id="sampleContentC">
                  <table>
                    <tbody>
                      <% @good_rank.each.with_index(1) do |good_rank, i| %>
                          <tr>
                            <td colspan="2"><%= "第#{i}位" %>：<%=link_to "#{good_rank.title}", topic_path(good_rank) ,class: "ranking_box"%></td>
                          </tr>
                          <tr class="ranking_border">
                            <td><%= attachment_image_tag good_rank.user, :profile_image, size: '50x50', fallback: "no_image_top.jpg", class: "" %></td>
                            <td>score：<%= good_rank.good_count %></td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
              </div>
        </div>
    </div>

    <div class="col-md-12 text-center">
        <%= paginate @topics, class: "pagenate" %>
    </div>
</div>


<div class="col-md-12 border_line">
</div>

app/views/topics/show.html.erb
<div class="col-md-12 second_nav">
    <div class="col-md-10 col-md-offset-1">
        <div class="col-md-9">
            <%if @topic.user != current_user %>
                <% if user_signed_in? %>
                    <%= link_to "クリップ", add_topic_path(@topic.id), method: :post,class: "square_btn" %>
                <% end %>
            <% end %>
              <h2><%= @topic.title %></h2>
              <div class="pull-left"><%=link_to user_path(@topic.user.id) do %><%= attachment_image_tag @topic.user, :profile_image, fallback: "no_image_top.jpg",class: "user_icon" ,size: '30x30' %><%= @topic.user.name %><% end %></div><div class="pull-right"><%= @topic.created_at.strftime("%m#{"月"}%d#{"日"}")%></div>
        </div>


        <div class="col-md-3">
              <div class="col-md-4 text-left">
                <h5 class="ranking_display">PV</h5>
                <h5 class="ranking_display"><%= @topic.page_count %></h5>
                <h5 class="ranking_display">VIEWS</h5>
              </div>
              <div class="col-md-4 text-left">
                <h5 class="ranking_display">できた人</h5>
                <h5 class="ranking_display"><%= @topic.topic_goods.count %></h5>
                <h5 class="ranking_display">PERSONS</h5>
              </div>
              <div class="col-md-4 text-left">
                <h5 class="ranking_display">できない人</h5>
                <h5 class="ranking_display"><%= @topic.topic_bads.count %></h5>
                <h5 class="ranking_display">PERSONS</h5>
              </div>


            <div class="col-md-6">
                <%if @topic.user != current_user %>
                    <% if user_signed_in? %>
                        <% if current_user.already_topic_bad?(@topic) == false %>
                            <% if user_signed_in? %>
                                <div>
                                    <% if current_user.already_topic_good?(@topic) %>
                                        <%= button_to '取り消す', topic_topic_good_path(@topic), method: :delete, class: "square_btn_good" %>
                                    <% else %>
                                        <%= form_for [@topic, @topic_good] do |f| %>
                                            <% if @topic_good.errors.any? %>
                                                <% @topic_good.errors.full_messages.each do |msg| %>
                                                    <li style="color: red;"><%= msg %></li>
                                                <% end %>
                                            <% end %>
                                            <%= f.submit 'できた',class: "square_btn_good" %>
                                        <% end %>
                                    <% end %>
                                </div>
                            <% end %>
                        <% end %>
                    <% end %>
                 <% end %>
            </div>




            <div class="col-md-6">
             <%if @topic.user != current_user %>
                <% if user_signed_in? %>
                    <% if current_user.already_topic_good?(@topic) == false %>
                        <% if user_signed_in? %>
                            <% if current_user.already_topic_bad?(@topic) %>
                                <%= button_to '取り消す',topic_topic_bad_path(@topic), method: :delete, class: "square_btn_bad" %>
                            <% else %>
                                <%= form_for [@topic, @topic_bad] do |f| %>
                                    <% if @topic_bad.errors.any? %>
                                        <% @topic_bad.errors.full_messages.each do |msg| %>
                                            <li style="color: red;"><%= msg %></li>
                                        <% end %>
                                    <% end %>
                                <%= f.submit 'できない',class: "square_btn_bad" %>
                                <% end %>
                            <% end %>
                        <% end %>
                    <% end %>
                <% end %>
             <% end %>
            </div>
        </div>
    </div>
</div>


 <div class="col-md-12 third_nav">
        <div class="col-md-10 col-md-offset-1">
            <div class="tag">
                 <ul class="ul">
                    <% @topic.categories.each do |category| %>
                         <li class="li">
                        <%= link_to "#{category.category_name}", categories_path(category_name: category.category_name), class: "btn btn-primary" %>
                         </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>

 <div class="col-md-12">
    <div class="col-md-10 col-md-offset-1">
          <% if flash[:notice] %>
            <label style="color:red;"><%= flash[:notice] %></label>
          <% end %>
    </div>
</div>

<div class="">
    <div class="col-md-10 col-md-offset-1">
        <div class="col-md-12">
            <div class="col-md-12 ogp">
                <%= link_to "#{@topic.url}" do %>
                  <div class="col-md-2 text-center">
                    <% if  @topic.url.include?("teratail") then %>
                            <%= image_tag 'teratail_top.jpg',:size =>'100x100' %>
                    <% elsif @topic.url.include?("qiita") then %>
                            <%= image_tag 'Qiita.png',:size =>'100x100' %>
                    <% else %>
                            <%= image_tag 'no_image.png',:size =>'100x100' %>
                    <% end %>
                  </div>
                  <% end %>

                  <div class="col-md-10">
                        <div class="col-md-12 show_title">
                            <%= link_to "#{@topic.url}" do %>
                                <%= @topic.title %>
                            <% end %>
                        </div>

                        <div class="col-md-12 show_url">
                            <%= @topic.url %>
                        </div>

                        <div class="col-md-12 show_paragraph">
                            <%= @topic.paragraph %>
                        </div>

                         <div class="col-md-6 show_author">
                            <% if  @topic.url.include?("qiita") then %>
                                <%= link_to "https://qiita.com/#{@topic.author.delete!("@")}" do %>
                                    @<%= @topic.author %>
                                <% end %>

                            <% elsif @topic.url.include?("teratail") then %>
                                <%= link_to "https://teratail.com/users/#{@topic.author}" do %>
                                    @<%= @topic.author %>
                                <% end %>

                            <% else %>

                            <% end %>
                        </div>

                        <div class="show_posted_day">
                            <%= @topic.posted_day %>
                        </div>
                  </div>
              </div>
        </div>




        <div class="col-md-12">
             <% if @topic.paragraph.blank? == false %>
                    <h5 class="topic_margin">記事本文</h5>
                    <div style="white-space:pre-wrap" class="col-md-12 body_box"><%= @topic.paragraph %></div>
              <% end %>
        </div>


         <%= attachment_image_tag @topic, :topic_image , class: "col-md-12 topic_image topic_margin"  %>


        <div class="col-md-12">
            <% if @topic.body.blank? == false %>
                    <h5 class="topic_margin">修正前コード</h5>
                    <div  style="white-space:pre-wrap" class="col-md-12 body_box"><%= @topic.body %></div>
            <% end %>

            <% if @topic.re_body.blank? == false %>
                    <h5 class="topic_margin">修正後コード</h5>
                    <div  style="white-space:pre-wrap" class="col-md-12 body_box"><%= @topic.re_body %></div>
             <% end %>
        </div>

        <div class="col-md-12 main_icon">
            <div class="col-md-6">
                <% if @topic.user == current_user || admin_signed_in? %>
                    <%= link_to edit_topic_path(@topic),class: "btn btn-default" do %>
                <i class="glyphicon glyphicon-pencil">編集</i>
                <% end %>
                <% end %>
            </div>


            <div class="col-md-6">
                <% if @topic.user == current_user || admin_signed_in? %>
                    <i class="glyphicon glyphicon-trash show_icon"><label>
                        <%= link_to "削除", topic_path(@topic),:confirm => '削除しますか?',:method => :delete  %>
                     </label></i>
                       <% end %>
                    <i class="glyphicon glyphicon-thumbs-up show_icon"><label><%= @topic.topic_goods.count %></label></i>
                    <!-- <i class="glyphicon glyphicon-paperclip show_icon"><label>3</label></i> -->

                <i class="glyphicon glyphicon-stats show_icon"><label>
                    <%# @num = @topic.bad_count + @topic.good_count %>
                    <% if @topic.percentage.nan? %>
                    <%# if ((@topic.good_count.to_f.round(1)/ (@num).round(1) ) * 100).round(1).nan? %>
                    <%= 0 %>%
                    <% else %>
                    <%= @topic.percentage.to_i %>%
                    <% end %>
                </label></i>

            </div>
        </div>


        <!-- ====================コメント機能======================= -->
        <% if user_signed_in? %>
            <div class="col-md-12">
                <!-- <%#= @topic.topic_comments.count %>件コメント -->
                <hr>
                <% @topic.topic_comments.each do |topic_comment| %>
                    <li>コメントID：<%= topic_comment.id %></li>
                    <li>投稿者：<%= topic_comment.user.name %></li>
                    <li style="white-space:pre-wrap" class="comment_box"><%= topic_comment.comment  %>
                        <h5 class="pull-right">投稿日<%= topic_comment.created_at.strftime('%Y/%m/%d') %>
                         <% if topic_comment.user == current_user || current_admin %>
                        <%= link_to  topic_topic_comment_path(@topic, topic_comment),:confirm => 'コメントを削除しますか?',:method => :delete  do %><i class="glyphicon glyphicon-trash show_icon">削除</i>
                        <% end %>
                        <% end %>
                        </h5>
                    </li>

                     <hr>
                <% end %>
                <%= form_for [@topic, @topic_comment] do |f| %>
                    <div class="">
                        <%= f.text_area :comment, class: "form-control",placeholder: "コメントをここに" %>
                    </div>
                    <%= f.submit "送信する", class: "btn btn-default" %>
                <% end %>
            </div>
        <% end %>
        </div>
        <!-- ====================コメント機能======================= -->
    </div>
</body>


<div class="col-md-12 border_line">
</div>

<div class="col-md-12 second_footer">
    <div class="col-md-10 col-md-offset-1">
        <div class="tag_footer">
            <ul class="ul_footer">
                <li class="li_footer">
                    <span class="tag_list">タグ一覧</span>
                </li>
            <% @topic.tags.each do |tag| %>
                <li class="li_footer">
                    <%= link_to "#{tag.tag_name}", tags_path(tag_name: tag.tag_name),class: "tag_list" %>
                </li>
            <% end %>
            </ul>
        </div>
    </div>
</div>