config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}


namespace :admins do
   get 'users/top' => 'users#top', as: 'top'
  resources :users
  resources :topics
  resources :contacts
end

resources :contacts, only: [:create, :destroy]

  resources :users do
     member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  get 'topics/password' => 'topics#password', as: 'topic_password'
  get 'topics/top' => 'topics#top', as: 'top'
  resources :topics do
        member do
      post "add", to: "clips#create"
    end
        collection do
      post 'confirm'
    end
    resources :topic_goods, only: [:create, :destroy]
    resources :topic_bads, only: [:create, :destroy]
    resources :topic_comments, only: [:create, :destroy]
  end

  resources :tags
  resources :categories
  resources :clips, only: [:destroy]

  root 'topics#top'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
attachment :profile_image

# 記事とユーザーの関係1:N
has_many :topics

# グッド機能
has_many :topics, dependent: :destroy
has_many :topic_goods, dependent: :destroy
has_many :good_posts, through: :topic_goods, source: :post
def already_topic_good?(topic)
	self.topic_goods.exists?(topic_id: topic.id)
end

# バッド機能
has_many :topics, dependent: :destroy
has_many :topic_bads, dependent: :destroy
has_many :bad_posts, through: :topic_bads, source: :post
def already_topic_bad?(topic)
	self.topic_bads.exists?(topic_id: topic.id)
end

#コメント機能
# has_many :topics すでに定義済み
has_many :topic_comments, dependent: :destroy


# クリップ機能
has_many :clips
has_many :clip_topics, through: :clips, source: :topic

# フォロー機能
has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

 has_many :followings, through: :following_relationships

 has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

 has_many :followers, through: :follower_relationships

 validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }


  def soft_delete
      update(deleted_at: Time.now)
  end

  def active_for_authentication?
    !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end



  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end




end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
 before_action :authenticate_admin!
 layout 'admin.application'


  def top
    @users = User.all.order(updated_at: :desc)
    @topics = Topic.all.order(created_at: :desc)
    @contacts = Contact.all.order(created_at: :desc)
  end

  def index
  	@users = User.all.order(created_at: :desc)
  end

	private
		def user_params
			params.require(:user).permit(:name , :email , :profile_image)
		end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :screen_user
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

# def create
#     auth_options = { :recall => 'topics#top', :scope => :user }
#     resource = warden.authenticate!(auth_options)
# end


  # 認証が失敗した場合に呼び出されるアクション
  def failed
    # warden で出力されたエラーを保存する
    flash[:notice] = "ログインに失敗しました。"
    redirect_to topics_path
  end

  protected
  def auth_options
    # 失敗時に recall に設定したパスのアクションが呼び出されるので変更
    # { scope: resource_name, recall: "#{controller_path}#new" } # デフォルト
    { scope: resource_name, recall: "#{controller_path}#failed" }
  end

def screen_user
      unless user_signed_in? || admin_signed_in?
        redirect_to root_path
      end
    end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# before_action :authenticate_user!
	before_action :screen_user


	def show
		@user = User.find(params[:id])
		@topics_kaminari_all = @user.topics
		@topics_kaminari = Kaminari.paginate_array(@topics_kaminari_all).page(params[:page]).per(5)

		@clips = Clip.where("user_id = ?", @user)
		@clips_kaminari_all = @user.clip_topics
		@clips_kaminari = Kaminari.paginate_array(@clips_kaminari_all).page(params[:page]).per(5)

		@user.update(follower_count: @user.followers.count)
	end

	def edit
		@users = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_path(@user.id)
	end

  def destroy
      @user = User.find(params[:id])
      @user.soft_delete
      sign_out(@user)
      redirect_to root_path
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  
	private
		def user_params
			params.require(:user).permit(:name , :email , :profile_image)
		end

	def screen_user
      unless user_signed_in? || admin_signed_in?
        redirect_to root_path
      end
    end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper

def current_user?(user)
     user == current_user
  end

end

app/views/admins/users/edit.html.erb
<h1>Admins::Users#edit</h1>
<p>Find me in app/views/admins/users/edit.html.erb</p>

app/views/admins/users/index.html.erb
<div class="row admin_row">
    <div class="col-md-11 col-md-offset-1">
    <h1>Dashboard</h1>
      <div class="col-md-11 admin_box_second3">
        <h2 class="admin_title"><i class="glyphicon glyphicon-chevron-right"></i>Users</h2>
            <div class="col-md-12  dashboard_box">
               <% @users.each do |user| %>
                    <div class="col-md-1">
                    <%= user.id %>
                    </div>

                    <div class="col-md-3">
                    <%= link_to "#{user.name}",user_path(user) %>
                    </div>

                    <div class="col-md-3">
                    <%= user.email %>
                    </div>

                    <div class="col-md-3">
                    <%= simple_time(user.updated_at) %>
                    </div>

                    <div class="col-md-2">
                    <%= link_to "削除",  admins_user_path(user), method: :delete %>
                    </div>
                <% end %>
            </div>
       </div>
   </div>
</div>

app/views/admins/users/show.html.erb
<h1>Admins::Users#show</h1>
<p>Find me in app/views/admins/users/show.html.erb</p>

app/views/admins/users/top.html.erb
<div class="row admin_row">
    <div class="col-md-11 col-md-offset-1">
    <h1>Dashboard</h1>
   	<%= link_to admins_users_path do %>
   	 <div class="col-md-3 admin_box1" >
	    	<div class="col-md-4"><h1><i class="glyphicon glyphicon-user"></i></h1></div>
	    	<div class="col-md-8">
	    		<div class="col-md-12 count">
	    		<%= User.count %>
		    	</div>
	    		<div class="col-md-12 text_name">
	    		Users
		    	</div>
	    	</div>
	    	<div class="col-md-12">
		    	<div class="col-md-6 detail">view detail</div>
		    	<div class="col-md-6 icon_arrow-right"><i class="glyphicon glyphicon-circle-arrow-right"></i></div>
		    	</div>
	  </div>
    <% end %>

 	<%= link_to admins_topics_path do %>
    <div class="col-md-3 col-md-offset-1 admin_box2">
	    	<div class="col-md-4"><h1><i class="glyphicon glyphicon-list-alt"></i></h1></div>
			<div class="col-md-8">
				<div class="col-md-12 count">
				<%= Topic.count %>
				</div>
				<div class="col-md-12 text_name">
		   		Topics
		   		</div>
	    	</div>
	    	<div class="col-md-12">
	    	<div class="col-md-6 detail">view detail</div>
			<div class="col-md-6 icon_arrow-right"><i class="glyphicon glyphicon-circle-arrow-right"></i></div>
			</div>
    </div>
    <% end %>

 	<%= link_to admins_contacts_path do %>
     <div class="col-md-3 col-md-offset-1 admin_box3">
	     	<div class="col-md-6"><h1><i class="glyphicon glyphicon-envelope"></i></h1></div>
			<div class="col-md-6">
				<div class="col-md-12 count">
				<%= Contact.count %>
				</div>
				<div class="col-md-12 text_name">
				Contacts
				</div>
			</div>
			<div class="col-md-12">
			<div class="col-md-6 detail">view detail</div>
			<div class="col-md-6 icon_arrow-right"><i class="glyphicon glyphicon-circle-arrow-right"></i></div>
			</div>

    </div>
     <% end %>

    </div>
     <div class="col-md-11 col-md-offset-1">
     	<div class="col-md-7 admin_box_second1">
	     	<h2 class="admin_title"><i class="glyphicon glyphicon-chevron-right"></i>Contacts</h2>
     		<div class="col-md-12">
     			<% @contacts.each do |contact| %>
     			<div class="col-md-12 dashboard_box_second">
     				<%= link_to "#{contact.body}",admins_contact_path(contact) %>
     				</div>
     			<div class="col-md-12 dashboard_box_second time_day"><%= simple_time(contact.created_at) %></div>
     			<% end %>
     		</div>
     	</div>



     	<div class="col-md-3 col-md-offset-1 admin_box_second2">
     		<h2 class="admin_title"><i class="glyphicon glyphicon-chevron-right"></i>Users</h2>
     		<div class="col-md-12 dashboard_box">
     			<% @users.each do |user| %>
		     			<div class="col-md-12 dashboard_box_second">
							<%= link_to "#{user.name}",user_path(user) %>
		     				</div>
		     				<div class="col-md-12 dashboard_box_second time_day"><%= simple_time(user.updated_at) %></div>
	     			<% end %>
     		</div>
     	</div>


       <div class="col-md-11 admin_box_second3">
       		<h2 class="admin_title"><i class="glyphicon glyphicon-chevron-right"></i>Topics</h2>
       		<div class="col-md-12  dashboard_box">
				<% @topics.each do |topic| %>
				<div class="col-md-12 dashboard_box_second">
					<%=link_to "#{topic.title}",topic_path(topic) %>
					</div>
				<div class="col-md-12 dashboard_box_second time_day"><%= simple_time(topic.created_at) %></div>
				<% end %>
       		</div>
       </div>
	</div>
</div>