config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}


namespace :admins do
   get 'users/top' => 'users#top', as: 'top'
  resources :users
  resources :topics
  resources :contacts
end

resources :contacts, only: [:create, :destroy]

  resources :users do
     member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  get 'topics/password' => 'topics#password', as: 'topic_password'
  get 'topics/top' => 'topics#top', as: 'top'
  resources :topics do
        member do
      post "add", to: "clips#create"
    end
        collection do
      post 'confirm'
    end
    resources :topic_goods, only: [:create, :destroy]
    resources :topic_bads, only: [:create, :destroy]
    resources :topic_comments, only: [:create, :destroy]
  end

  resources :tags
  resources :categories
  resources :clips, only: [:destroy]

  root 'topics#top'
end

app/models/tag.rb
class Tag < ApplicationRecord
belongs_to :topic

# validates :tag_name, presence: true
# validates :tag_name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tag_name = tag_params
		@tags = Topic.joins(:tags).where('tag_name = ?', @tag_name )

  if params[:search].present?
      @topic = Topic.search(params[:search])
       @topic_search = Topic.search(params[:search])
      if @topic == []
        @topic = Topic.all
        flash.now[:notice] = "検索に一致する商品がありませんでした。"
      end
    else
      @topic = Topic.all
    end

    @topics = Kaminari.paginate_array(@tags).page(params[:page]).per(10)

    @good_rank = Topic.find(TopicGood.group(:topic_id).order('count(topic_id) desc').limit(10).pluck(:topic_id))
    @page_rank = Topic.order('page_count DESC').limit(10)
    @user_rank = User.order('follower_count DESC').limit(10)

    @all_good_count = 0
    @all_bad_count = 0
    @total = 0
    @num = 0
    @percent = 0
    @one_total = 0

    @tags.each do |topic|

    # 全体のできない数
      @all_good_count += topic.good_count

    # 全体のできた数
      @all_bad_count += topic.bad_count

    # 個別の記事の投票数
      @num = topic.bad_count + topic.good_count

    end
    # 全体の記事の投票数
    @total = @all_bad_count + @all_good_count
    # 全体の記事の実装可能率
    @percent = (@all_good_count.to_f) / (@total)
    @new_topic = Topic.new


end

	private
	    def tag_params
	       params.permit(:tag_name)[:tag_name]
	    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<% if user_signed_in? %>
<div class="col-md-12 topic_registration">
<%= form_for @new_topic, url: confirm_topics_path do |f|  %>
<%= f.url_field :url,class: "col-md-10" ,:placeholder => "URLで記事を登録できます。" %>
<%= f.submit "登録", class: "col-md-2 btn-default bt-samp31" %>
<% end %>
</div>
<% end %>

<div class="col-md-12 second_nav">
    <div class="col-md-10 col-md-offset-1">

        <div class="col-md-3 col-md-offset-1 second_nav_box">
            <div class="col-md-12 text-center nav_box_text">
              登録ユーザー
            </div>
            <div class="col-md-12 text-center">
              <h2 class="h2_count"><%= User.count %><h6 class="h2_count">人</h6></h2>
            </div>
        </div>

         <div class="col-md-3 col-md-offset-1 second_nav_box">
            <div class="col-md-12 text-center nav_box_text">
              記事総数
            </div>
            <div class="col-md-12 text-center">
              <h2 class="h2_count"><%= Topic.count %><h6 class="h2_count">個</h6></h2>
            </div>
        </div>

        <div class="col-md-3 col-md-offset-1 second_nav_box">
            <div class="col-md-12 text-center nav_box_text">
             選択タグ実装可能率
            </div>
            <div class="col-md-12 text-center">
             <% if (@percent * 100).round(1).nan? %>
                  <h2 class="h2_count"><%= "0" %><h6 class="h2_count">%</h6></h2>
              <% else %>
                  <h2 class="h2_count"><%= (@percent * 100).round(0) %><h6 class="h2_count">%</h6></h2>
              <% end %>
            </div>
        </div>
    </div>
</div>




<div class="col-md-12 search_area">
        <%= form_tag topics_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search] ,class: "col-md-10 topic_form_index",:placeholder => "記事の検索ができます。" %>
            <%= submit_tag '検索', :name => nil , class: "btn btn-default col-md-2 topic_submit_index bt-samp31" %>
        <% end %>
  </div>


<div class="">
    <div class="col-md-7 col-md-offset-1">
       <h3> <%= @tag_name %></h3>
          <% if flash[:notice] %>
        <label style="color:red;"><%= flash[:notice] %></label>
      <% end %>
        <table class="table">
            <tbody>
                <% @topics.each do |topic| %>
                    <tr>
                        <% if topic.percentage.nan? %>
                              <td class="per_dis" nowrap rowspan="2"><%= 0 %>%</td>
                          <% else %>
                              <td class="per_dis" nowrap rowspan="2"><%= topic.percentage.to_i %>%</td>
                        <% end %>
                        <td class="topic_title_index" colspan="3">
                            <% if topic.is_new %>
                                <label class="new_label">新着</label>
                            <% end %>
                            <%= link_to "#{topic.title}", topic_path(topic),class: "topic_title_index" %></td>
                        <td nowrap ><% if user_signed_in? %><%= link_to "クリップ", add_topic_path(topic.id), method: :post %><% end %></td>
                    </tr>
                    <tr>
                        <td nowrap>
                          <i class="glyphicon glyphicon-thumbs-up"></i><%= topic.good_count %>
                          <i class="glyphicon glyphicon-thumbs-down"></i><%= topic.bad_count %>
                        </td>
                        <td nowrap><%= topic.page_count %>PV</td>
                        <td>
                            <% topic.categories.each do |category| %>
                                <%= link_to "#{category.category_name}", categories_path(category_name: category.category_name)  %>
                            <% end %>
                        </td>
                        <td nowrap><%= topic.user.name %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="col-md-3">
       <h3>ランキング</h3>
        <!-- タブ・メニュー -->
        <ul class="nav nav-tabs">
              <li class="active tab_size"><a class="tab_font_size" href="#sampleContentA" data-toggle="tab">ユーザー</a></li>
              <li class="tab_size"><a class="tab_font_size" href="#sampleContentB" data-toggle="tab">記事</a></li>
              <li class="tab_size"><a class="tab_font_size" href="#sampleContentC" data-toggle="tab">いいね</a></li>
        </ul>

        <!-- タブ内容 -->
        <div class="tab-content">
              <div class="tab-pane active" id="sampleContentA">
                  <table class="col-md-12">
                    <tbody>
                      <% @user_rank.each.with_index(1) do |user_rank, i| %>
                          <tr>
                            <td><%= "第#{i}位" %>：</td>
                            <td><%=link_to "#{user_rank.name}", user_path(user_rank) %></td>
                          </tr>
                          <tr class="ranking_border">
                             <td><%= attachment_image_tag user_rank, :profile_image, size: '50x50', fallback: "no_image_top.jpg", class: "" %></td>
                            <td>followers：<%= user_rank.follower_count %></td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
              </div>


              <div class="tab-pane" id="sampleContentB">
                  <table>
                    <tbody>
                      <% @page_rank.each.with_index(1) do |page_rank, i| %>
                          <tr>
                            <td colspan="2"><%= "第#{i}位" %>：<%=link_to "#{page_rank.title}", topic_path(page_rank) %></td>
                          </tr>
                          <tr class="ranking_border">
                            <td><%= page_rank.user.name %></td>
                            <td>views：<%= page_rank.page_count %></td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
              </div>


              <div class="tab-pane" id="sampleContentC">
                  <table>
                    <tbody>
                      <% @good_rank.each.with_index(1) do |good_rank, i| %>
                          <tr>
                            <td colspan="2"><%= "第#{i}位" %>：<%=link_to "#{good_rank.title}", topic_path(good_rank) ,class: "ranking_box"%></td>
                          </tr>
                          <tr class="ranking_border">
                            <td><%= attachment_image_tag good_rank.user, :profile_image, size: '50x50', fallback: "no_image_top.jpg", class: "" %></td>
                            <td>score：<%= good_rank.good_count %></td>
                          </tr>
                      <% end %>
                    </tbody>
                  </table>
              </div>
        </div>
    </div>
    <div class="col-md-12 text-center">
        <%= paginate @topics, class: "pagenate" %>
    </div>
</div>



<div class="col-md-12 border_line">
</div>