config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}


namespace :admins do
   get 'users/top' => 'users#top', as: 'top'
  resources :users
  resources :topics
  resources :contacts
end

resources :contacts, only: [:create, :destroy]

  resources :users do
     member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  get 'topics/password' => 'topics#password', as: 'topic_password'
  get 'topics/top' => 'topics#top', as: 'top'
  resources :topics do
        member do
      post "add", to: "clips#create"
    end
        collection do
      post 'confirm'
    end
    resources :topic_goods, only: [:create, :destroy]
    resources :topic_bads, only: [:create, :destroy]
    resources :topic_comments, only: [:create, :destroy]
  end

  resources :tags
  resources :categories
  resources :clips, only: [:destroy]

  root 'topics#top'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

has_many :topic_categories
has_many :topics, :through => :topic_categories

end

app/models/clip.rb
class Clip < ApplicationRecord
belongs_to :user
belongs_to :topic


validates :topic_id,:uniqueness => {:scope =>:user_id }

end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :email, presence: true
	validates :body, presence: true
	validates :title, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

belongs_to :follower, class_name: "User"
belongs_to :following, class_name: "User"
validates :follower_id, presence: true
validates :following_id, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
belongs_to :topic

# validates :tag_name, presence: true
# validates :tag_name, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
#カウンティング用
is_impressionable
attachment :topic_image

# 記事とユーザーの関係1:N
belongs_to :user

# グッド機能
has_many(:topic_goods, {:dependent => :delete_all})
has_many :good_users, through: :topic_goods, source: :user

# バッド機能
has_many :topic_bads, dependent: :delete_all
has_many :bad_users, through: :topic_bads, source: :user

#コメント機能
belongs_to :user
has_many :topic_comments, dependent: :destroy

#カテゴリー
has_many :topic_categories
has_many :categories, :through => :topic_categories

#タグ機能
has_many :tags, inverse_of: :topic
accepts_nested_attributes_for :tags, allow_destroy: true


# クリップ機能
has_many :clips
has_many :users, through: :clips

validates :title, uniqueness: true
validates :url, uniqueness: true
# validates :tags, associated: true



  def is_new
    (3.days.ago..Time.current).cover?(Time.parse(self.created_at.to_s))
    # (1.minutes.ago..Time.current).cover?(Time.parse(self.created_at.to_s))
  end


  def self.search(search)
      if search.present?
        # binding.pry
        relation = Topic.joins(:tags)
        relations = relation.joins(:categories)
        relations.merge(Category.where(['category_name LIKE ?', "%#{search}%"])).or(relations.where(['tag_name LIKE ?', "%#{search}%"])).or(relations.where(['body LIKE ?', "%#{search}%"])).or(relations.where(['re_body LIKE ?', "%#{search}%"])).or(relations.where(['url LIKE ?', "%#{search}%"])).or(relations.where(['title LIKE ?', "%#{search}%"])).uniq
      else
        Topic.all
      end
  end

  def percentage
    total_count = self.bad_count + self.good_count
    return ((self.good_count.to_f.round(1)/ total_count.round(1) ) * 100).round(1)
  end
end

app/models/topic_bad.rb
class TopicBad < ApplicationRecord
  belongs_to :topic
  belongs_to :user


validates_uniqueness_of :topic_id, scope: :user_id
end

app/models/topic_category.rb
class TopicCategory < ApplicationRecord

belongs_to :category
belongs_to :topic

end

app/models/topic_comment.rb
class TopicComment < ApplicationRecord
belongs_to :user
belongs_to :topic

validates :comment, presence: true


end

app/models/topic_good.rb
class TopicGood < ApplicationRecord
  belongs_to :topic
  belongs_to :user

validates_uniqueness_of :topic_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
attachment :profile_image

# 記事とユーザーの関係1:N
has_many :topics

# グッド機能
has_many :topics, dependent: :destroy
has_many :topic_goods, dependent: :destroy
has_many :good_posts, through: :topic_goods, source: :post
def already_topic_good?(topic)
	self.topic_goods.exists?(topic_id: topic.id)
end

# バッド機能
has_many :topics, dependent: :destroy
has_many :topic_bads, dependent: :destroy
has_many :bad_posts, through: :topic_bads, source: :post
def already_topic_bad?(topic)
	self.topic_bads.exists?(topic_id: topic.id)
end

#コメント機能
# has_many :topics すでに定義済み
has_many :topic_comments, dependent: :destroy


# クリップ機能
has_many :clips
has_many :clip_topics, through: :clips, source: :topic

# フォロー機能
has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

 has_many :followings, through: :following_relationships

 has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

 has_many :followers, through: :follower_relationships

 validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }


  def soft_delete
      update(deleted_at: Time.now)
  end

  def active_for_authentication?
    !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end



  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end




end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topic_bads_helper.rb
module TopicBadsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

def current_user?(user)
     user == current_user
  end

end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/admin.application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minmemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <%= favicon_link_tag %>
  </head>

<body class='<%= "#{controller.controller_name}" %>'>
<header>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to topics_path do %>
          <%= image_tag 'logo.png', class: "logo" %>
          <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
              <li class="nav_list"><%= link_to "管理者トップ", admins_top_path %></li>
		           <li class="nav_list"><%= link_to "ログアウト", destroy_admin_session_path, :method => :delete %></li>
		  <% else %>
                <li class="nav_list"><%= link_to "トップ", root_path, class: "nav_registration"%></li>
	   	  <% end %>
          </ul>
        </div>
      </div>
    </nav>
</div>
</header>

<p id="notice"></p>

<%= yield %>

<footer>

</footer>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minmemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <%= favicon_link_tag %>
  </head>

<body class='<%= "#{controller.controller_name}" %>'>
<header>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to topics_path do %>
          <%= image_tag 'logo.png', class: "logo" %>
          <% end %>
        </div>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
               <li class="nav_list"><%=link_to "記事一覧", topics_path %></li>
                <li class="nav_list"><%=link_to "ユーザー情報", user_path(current_user.id) %></li>
		           <li class="nav_list"><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
		  <% else %>
    		  			<li><%= f.email_field :email, autofocus: true, autocomplete: "email", class: "nav_form",:placeholder => "Email"  %></li>
		            <li><%= f.password_field :password, autocomplete: "off", class: "nav_form" ,:placeholder => "Password"  %></li>
		            <li><%= f.submit "Log in" , class: "nav_form" %></li>
                <li class="nav_list"><%= link_to "新規登録", root_path, class: "nav_registration"%></li>
	   	  <% end %>
          </ul>
        </div>
      </div>
    </nav>
<% end %>
</div>
</header>

<p id="notice"></p>

<%= yield %>

<% if admin_signed_in? %>
<div class="col-md-12">
    管理者ログイン中
</div>
<% end %>
<footer>
    <div class="col-md-12 footer">
        <div class="col-md-10 col-md-offset-1">
            <div class="col-md-3">
                <ul>
                    <%= image_tag 'logo.png' ,class: "col-md-12 footer_logo" %>
                    <li class="col-md-12 sitemap">-Site Map-</li>
                     <% if user_signed_in? == false%>
                    <li class="col-md-12 sitemap forgot_password">
                    ・<%= link_to "Forgot password" , topic_password_path, class: "sitemap" %>
                  </li>
                    <% end %>
                </ul>
            </div>

            <div class="col-md-4">
                <ul>
                    <li class="col-md-12 sitemap sns">-My Web Site SNS-</li>
                    <li class="col-md-12 sitemap">・<%= link_to "GitHub" , "https://github.com/hayato1118/" ,class: "sitemap" %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Facebook" , "https://www.facebook.com/memo.minnano.9" ,class: "sitemap"  %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Twitter" , "https://twitter.com/minnano_memo" ,class: "sitemap"  %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Instagram" , "https://www.instagram.com/minnano_memo/" ,class: "sitemap"  %></li>
                </ul>
            </div>

            <div class="col-md-5">
                <ul>
                    <li class="contact_index">-Contact-</li>
                     <%= form_for @contact, url: contacts_path , html: {method: "POST"} do |f| %>
                    <li><%= f.text_field :title ,class: "col-md-12 contact contact_title",:placeholder => "Title"  %></li>
                    <li><%= f.email_field :email,class: "col-md-12 contact contact_email",:placeholder => "Email"  %></li>
                    <li><%= f.text_area :body ,class: "col-md-12 contact contact_body",:placeholder => "Message"  %></li>
                    <li><%= f.submit "Message Sending",class: "col-md-12 contact contact_submit" %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</footer>
</html>

app/views/layouts/index.application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minmemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <%= favicon_link_tag %>
  </head>

<body class='<%= "#{controller.controller_name}" %>'>
<header>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to root_path do %>
          <%= image_tag 'logo.png', class: "logo" %>
          <% end %>
        </div>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
               <li class="nav_list"><%=link_to "記事一覧", topics_path %></li>
                <li class="nav_list"><%=link_to "ユーザー情報", user_path(current_user.id) %></li>
		           <li class="nav_list"><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
		  <% else %>
    		  			<li><%= f.email_field :email, autofocus: true, autocomplete: "email", class: "nav_form",:placeholder => "Email"  %></li>
		            <li><%= f.password_field :password, autocomplete: "off", class: "nav_form" ,:placeholder => "Password"  %></li>
		            <li><%= f.submit "Log in" , class: "nav_form" %></li>
                <li class="nav_list"><%= link_to "新規登録", root_path, class: "nav_registration"%></li>
	   	  <% end %>
          </ul>
        </div>
      </div>
    </nav>
<% end %>
</div>
</header>

<p id="notice"></p>

<%= yield %>
<% if admin_signed_in? %>
<div class="col-md-12">
    管理者ログイン中
</div>
<% end %>


<footer>
    <div class="col-md-12 footer">
        <div class="col-md-10 col-md-offset-1">
            <div class="col-md-3">
                <ul>
                    <%= image_tag 'logo.png' ,class: "col-md-12 footer_logo" %>
                    <li class="col-md-12 sitemap">-Site Map-</li>
                     <% if user_signed_in? == false%>
                    <li class="col-md-12 sitemap forgot_password">
                    ・<%= link_to "Forgot password" , topic_password_path, class: "sitemap" %>
                  </li>
                    <% end %>
                </ul>
            </div>

            <div class="col-md-4">
                <ul>
                    <li class="col-md-12 sitemap sns">-My Web Site SNS-</li>
                    <li class="col-md-12 sitemap">・<%= link_to "GitHub" , "https://github.com/hayato1118/" ,class: "sitemap" %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Facebook" , "https://www.facebook.com/memo.minnano.9" ,class: "sitemap"  %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Twitter" , "https://twitter.com/minnano_memo" ,class: "sitemap"  %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Instagram" , "https://www.instagram.com/minnano_memo/" ,class: "sitemap"  %></li>
                </ul>
            </div>

            <div class="col-md-5">
                <ul>
                    <li class="contact_index">-Contact-</li>
                    <%= form_for @contact, url: contacts_path , html: {method: "POST"} do |f| %>
                    <li><%= f.text_field :title ,class: "col-md-12 contact contact_title",:placeholder => "Title"  %></li>
                    <li><%= f.email_field :email,class: "col-md-12 contact contact_email",:placeholder => "Email"  %></li>
                    <li><%= f.text_area :body ,class: "col-md-12 contact contact_body",:placeholder => "Message"  %></li>
                    <li><%= f.submit "Message Sending",class: "col-md-12 contact contact_submit" %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</footer>
</html>

app/views/layouts/password.application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minmemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <%= favicon_link_tag %>
  </head>

<body class='<%= "#{controller.controller_name}" %>'>
<header>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to topics_path do %>
          <%= image_tag 'logo.png', class: "logo" %>
          <% end %>
        </div>
        <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post })  do |f| %>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
               <li class="nav_list"><%=link_to "記事一覧", topics_path %></li>
                <li class="nav_list"><%=link_to "ユーザー情報", user_path(current_user.id) %></li>
		           <li class="nav_list"><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
		  <% else %>
	  			　　<li><%= f.email_field :email, autofocus: true, autocomplete: "email",class: "nav_form",:placeholder => "Email"   %></li>
		            <li><%= f.submit "reset password",class: "nav_form"  %></li>
                <li class="nav_list"><%= link_to "新規登録", root_path, class: "nav_registration"%></li>
	   	  <% end %>
          </ul>
        </div>
      </div>
    </nav>
<% end %>
</div>
</header>

<p id="notice"></p>

<%= yield %>
<% if admin_signed_in? %>
<div class="col-md-12">
    管理者ログイン中
</div>
<% end %>
<footer>
    <div class="col-md-12 footer">
        <div class="col-md-10 col-md-offset-1">
            <div class="col-md-3">
                <ul>
                    <%= image_tag 'logo.png' ,class: "col-md-12 footer_logo" %>
                    <li class="col-md-12 sitemap">-Site Map-</li>
                     <% if user_signed_in? == false%>
                    <li class="col-md-12 sitemap forgot_password">
                    ・<%= link_to "Forgot password" , topic_password_path, class: "sitemap" %>
                  </li>
                    <% end %>
                </ul>
            </div>

            <div class="col-md-4">
                <ul>
                    <li class="col-md-12 sitemap sns">-My Web Site SNS-</li>
                    <li class="col-md-12 sitemap">・<%= link_to "GitHub" , "https://github.com/hayato1118/" ,class: "sitemap" %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Facebook" , "https://www.facebook.com/memo.minnano.9" ,class: "sitemap"  %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Twitter" , "https://twitter.com/minnano_memo" ,class: "sitemap"  %></li>
                    <li class="col-md-12 sitemap">・<%= link_to "Instagram" , "https://www.instagram.com/minnano_memo/" ,class: "sitemap"  %></li>
                </ul>
            </div>

            <div class="col-md-5">
                <ul>
                    <li class="contact_index">-Contact-</li>
                     <%= form_for @contact, url: contacts_path , html: {method: "POST"} do |f| %>
                    <li><%= f.text_field :title ,class: "col-md-12 contact contact_title",:placeholder => "Title"  %></li>
                    <li><%= f.email_field :email,class: "col-md-12 contact contact_email",:placeholder => "Email"  %></li>
                    <li><%= f.text_area :body ,class: "col-md-12 contact contact_body",:placeholder => "Message"  %></li>
                    <li><%= f.submit "Message Sending",class: "col-md-12 contact contact_submit" %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</footer>
</html>

app/views/layouts/top.application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minmemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css" >
    <%= favicon_link_tag %>
  </head>

<body class="top">
<header>

<% if user_signed_in? %>
    <div class="col-md-4 header_logo">
      <%= link_to "みんなのメモ" ,topics_path,class: "header_list_a logo_top" %>
    </div>

    <div class="col-md-8 header_list">
      <%=link_to "記事一覧", topics_path,class: "header_list_a" %>
      <%=link_to "ユーザー情報", user_path(current_user.id),class: "header_list_a" %>
      <%=link_to "ログアウト", destroy_user_session_path, :method => :delete,class: "header_list_a" %>
    </div>

<% else %>

  <div class="col-md-6 header_logo">
      <%= link_to "みんなのメモ" ,topics_path,class: "header_list_a logo_top" %>
  </div>
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>
      <div class="col-md-6 header_list">
          <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "email_form",:placeholder => "Email"  %>

          <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
          <%= f.password_field :password, autocomplete: "off",:placeholder => "Password"  %>
          <%= f.submit "新規登録", class: "btn btn-default login_form"  %>
          <%= link_to "ログイン", topics_path,class: "header_list_a"  %>
      </div>
  <% end %>
<% end %>

</header>




</body>
<%= yield %>
<footer>
</footer>
</html>